# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Overcf < Formula
  desc "Cloudflare CLI for managing DNS and zones"
  homepage "https://github.com/OverseedAI/overcf"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/OverseedAI/overcf/releases/download/v0.1.2/overcf_darwin_amd64.tar.gz"
      sha256 "d624282c4cca9feaa8251b6aee3e15b04f81988e56ba878d18f2f2acbeb7e96c"

      define_method(:install) do
        bin.install "overcf"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/OverseedAI/overcf/releases/download/v0.1.2/overcf_darwin_arm64.tar.gz"
      sha256 "2faf25da12eea4accee49874fbc5cd6f4b89612842dc1e67b7411833041b4ba2"

      define_method(:install) do
        bin.install "overcf"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/OverseedAI/overcf/releases/download/v0.1.2/overcf_linux_amd64.tar.gz"
      sha256 "e0d9a001dcc1336bf235e2fb355627ef39695095a0cc2a0b9d8e85011198d21e"
      define_method(:install) do
        bin.install "overcf"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/OverseedAI/overcf/releases/download/v0.1.2/overcf_linux_arm64.tar.gz"
      sha256 "30c4e4b78ba9e641cfa4b34e9ed26e6325fc9d3843cf957ff5d1ff115b1deee6"
      define_method(:install) do
        bin.install "overcf"
      end
    end
  end

  test do
    system "#{bin}/overcf", "--version"
  end
end
