# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Overcf < Formula
  desc "Cloudflare CLI for managing DNS and zones"
  homepage "https://github.com/OverseedAI/overcf"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/OverseedAI/overcf/releases/download/v0.1.1/overcf_darwin_amd64.tar.gz"
      sha256 "22794535b0f990e2b08a01c2be169906ddb0573ae2f912248850e2a9660aef14"

      define_method(:install) do
        bin.install "overcf"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/OverseedAI/overcf/releases/download/v0.1.1/overcf_darwin_arm64.tar.gz"
      sha256 "48b1f6273292dcb366b34505bc2176430cf9603c15e77bf129862366f343dac4"

      define_method(:install) do
        bin.install "overcf"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/OverseedAI/overcf/releases/download/v0.1.1/overcf_linux_amd64.tar.gz"
      sha256 "fba1678a83113c5becd4220d1fdc8f78150eb60ff7c69e59966f8c69af57e3f2"
      define_method(:install) do
        bin.install "overcf"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/OverseedAI/overcf/releases/download/v0.1.1/overcf_linux_arm64.tar.gz"
      sha256 "45ff7d101569e411bc74c9834e08c1b237c5a28fe7f87e10894bb5bab1d38664"
      define_method(:install) do
        bin.install "overcf"
      end
    end
  end

  test do
    system "#{bin}/overcf", "--version"
  end
end
